# Generated by Django 4.1.1 on 2022-10-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Продукт')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('photo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фото')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('computers', 'Компьютеры'), ('notebooks', 'Ноутбуки'), ('mobile_phones', 'Мобильные телефоны'), ('toys', 'Игрушки'), ('furniture', 'Мебель')], default='other', max_length=100)),
                ('rest', models.IntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
