# Generated by Django 4.1.1 on 2022-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('computers', 'Компьютеры'), ('notebooks', 'Ноутбуки'), ('mobile_phones', 'Мобильные телефоны'), ('toys', 'Игрушки'), ('furniture', 'Мебель')], default='other', max_length=100, verbose_name='Категория'),
        ),
    ]
