# Generated by Django 4.1.1 on 2022-10-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderproductamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductamount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_orders', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderproductamount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_products', to='shop.product', verbose_name='Продукт'),
        ),
    ]
